version: '3.3'

services:
  application:
    container_name: application
    image: ubuntu:16.04
    networks:
      - uplawproject

  mysql:
    container_name: garung_mysql
    image: mysql:latest
    ports:
      - ${MYSQL_PORT}
    networks:
      - uplawproject
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    restart: always
      
  phpmyadmin:
    container_name: garung_phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    links:
      - mysql
      - phpfpm
    depends_on: 
      - mysql
    ports:
      - ${MYADMIN_PORT}
    networks:
      - uplawproject
    environment:
      PMA_HOST: ${PMA_HOST}
      PMA_PORT: ${PMA_PORT}

  nginx:
    container_name: garung_nginx
    image: nginx:latest
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
      - "${NGINX_HOST_HTTPS_PORT}:443"
    volumes:
      - ${NGINX_PATH}:/var/www/html
      - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
      - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
      - ${NGINX_CONFD_PATH}:/etc/nginx/conf.d
    networks:
      - uplawproject
    depends_on:
      - mysql

  phpfpm:
    container_name: garung_phpfpm
    image: mailcow/phpfpm:latest
    volumes:
      - ./var/www/html:/var/www/html
    links:
      - mysql
      - nginx
    networks:
      - uplawproject

  # php:
  #   container_name: garung_php
  #   image: php:7.2
  #   volumes:
  #     - ./var/www/html:/var/www/html
  #   networks:
  #     - uplawproject

  logs:
    container_name: garung_logs
    image: ubuntu:16.04
    volumes:
      - ./logs/nginx:/var/log/nginx
    networks:
      - uplawproject

networks:
  uplawproject:

volumes:
  mysql:
    driver: "local"
  phpmyadmin:
    driver: "local"
